# Generated by Django 3.1.1 on 2020-09-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='movieList',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
