# Generated by Django 3.1.1 on 2020-09-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200924_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='author',
            new_name='user',
        ),
    ]
